services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: symfony-app
    volumes:
      - .:/var/www/html:rw,cached # Mountowanie kodu do katalogu kontenera
      - ~/.ssh:/root/.ssh:ro  # Montowanie kluczy SSH z hosta
    ports:
      - "8000:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - symfony_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true  # Potrzebne, aby sesje działały poprawnie
    stdin_open: true
    entrypoint: ["/bin/bash", "-c", "ssh -f -N -L 8543:pgsql1.small.pl:5432 adamus1234@s1.small.pl & apache2-foreground"]

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    container_name: mercure
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
      MERCURE_SUBSCRIBER_JWT_KEY: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
      ALLOW_ANONYMOUS: '1'
      CORS_ALLOWED_ORIGINS: 'http://127.0.0.1:8000 http://127.0.0.1:3000 http://localhost:8000 http://localhost:3000'
      PUBLISH_ALLOWED_ORIGINS: 'http://127.0.0.1:8000 http://127.0.0.1:3000 http://localhost:8000 http://localhost:3000'
#command: /usr/bin/caddy run -config /etc/caddy/dev.Caddyfile
    ports:
      - "3000:80"
#    volumes:
#      - ./docker/mercure/Caddyfile:/etc/caddy/Caddyfile:ro # Twój plik Caddyfile
    networks:
      - symfony_network
    secrets:
      - jwt_key
    command: caddy run --config /etc/caddy/dev.Caddyfile

networks:
  symfony_network:
    name: symfony_network
    driver: bridge

secrets:
  jwt_key:
    file: ./config/jwt/private.pem